### PR TITLE
Using Third Part Repo to speedup

### PR DESCRIPTION
**Pull request by RedElectricity**
It can increase the success rate of compilation.(In China)

### CODE REVIEW

**Comment by TheSnowfield** [comment]
This commit is only applied to the region of China. 
It maybe not working for others over the world.
I'm fell so sorry to reject this PR.

**Comment by jasonren0403** [comment]
Rather than hardcoding it it should be made configurable

**Comment by TheSnowfield** [comment]
> Rather than hardcoding it should be made configurable

This issue is caused by npm and your network. 
You could change the source repository on your own device instead of in the repo.

**Comment by jasonren0403** [comment]
> > Rather than hardcoding it should be made configurable
> 
> This issue is caused by npm and your network.
> You could change the source repository on your own device instead of in this repo.

I knew that. What I mean is that providing the flag in runtime may make more sense.

**Pull request closed without merging**
